### ISSUE TITLE
32 bit support (Linux)?

### ISSUE THREAD

**Issue by khurshid-alam** [sindresorhus/anatine#105]
It would be great if we have 32 bit appimage support for Linux (Ubuntu).

**Comment by avernini** [comment]
Agreed

**Comment by sindresorhus** [comment]
You can build it yourself if you want, but not something I care about supporting.

**Comment by khurshid-alam** [comment]
@sindresorhus 

>You can build it yourself if you want...
It is not that simple....never was. I don't want deal with trouble of going through hundreds of compiling error and end up pulling my own hair out of frustration.

Beside I don't really understand the reason. On Linux all it takes to use multiarch (https://wiki.debian.org/Multiarch/HOWTO) to compile 32 bit on 64 bit machines. For debain its as simple as using a single line `arch : all` in debain/control.

>...but not something I care about supporting.

Alright. It's your project. You decide what to do with it.
