### ISSUE TITLE
npm run build:windows fails due to unix-style variable substitution

### ISSUE THREAD

**Issue by janis-kra** [sindresorhus/anatine#110]
When running `npm run build:windows` on my Windows 10 machine, I get the following error:

```
> anatine@0.5.1 build:windows D:\dev\workspace\privat\anatine
> electron-packager . --overwrite --asar --out=dist --ignore='^media$' --prune --platform=win32 --arch=ia32 --icon=static/Icon.ico --version-string.ProductName=$npm_package_productName --app-version=$npm_package_version && cd dist/Anatine-win32-ia32 && zip -ryq9 ../Anatine-windows-${npm_package_version}.zip *

Packaging app for platform win32 ia32 using electron v1.3.3
Fatal error: Unable to parse version string
 undefined
```

As suggested in https://github.com/electron-userland/electron-packager/issues/400 I changed the variable strings like `$npm_package_version` in the build script to `%npm_package_version%`, which did the trick for me. However, this probably breaks the cross-platform build on OSX, so I don't think it advisable to change the build:windows script to include this 'fix'. Maybe truly cross-platform build scripts just aren't there yet. Just wanted to give you a heads up.

**Comment by sindresorhus** [comment]
I'm working on switching to `electron-builder`. Will build on Windows then.
