### ISSUE TITLE
icon proposal

### ISSUE THREAD

**Issue by mcder3** [sindresorhus/anatine#119]
I would like to propose this icon that I created for the application.

![icon](https://cloud.githubusercontent.com/assets/1154298/19024296/0718bee8-88be-11e6-8c03-0a44a6761484.png)

![screenshot](https://cloud.githubusercontent.com/assets/1154298/19024309/5aa362b6-88be-11e6-9cd6-fcd88a4b2946.png)

**Comment by sindresorhus** [comment]
Looks very nice! Thanks for suggestion it. I think I'm gonna stick with the current one though, as it follows the Twitter blue color and has ties to the name (Anatine means duck).

**Comment by mcder3** [comment]
Now I understand why because a duck on the icon and thanks for answering :-)
