### ISSUE TITLE
😱 WHITE LINESSSSSSS 😱

### ISSUE THREAD

**Issue by kennetpostigo** [sindresorhus/anatine#122]
![screen shot 2016-11-04 at 6 40 40 pm](https://cloud.githubusercontent.com/assets/8888991/20024656/64b5dfb2-a2be-11e6-9160-447345042889.png)

Wondering if the anatine separators could match the caprine ones? Unless those white seperators are what you we're going for.

**Comment by sindresorhus** [comment]
PR welcome.
