### ISSUE TITLE
Localize and translate the main menu

### ISSUE THREAD

**Issue by claudioandre** [sindresorhus/anatine#133]
It is possible (and desirable) to translate the main application menu (menu.js). 

The idea is:
- create a new localize.js (or i18n.js, ...). No more than 20 LoC (lines of code);
- create some new files: en.js, fr.js, de.js, ..., containing the key: value translations;
- English will be the fallback language; 
- add the glue code (a few lines changes only in menu.js).

**If this _new feature_ can be accepted, I'm planning to submit a patch.**

[edit]
https://github.com/sindresorhus/anatine/compare/master...claudioandre:i18n?expand=1

**Comment by sindresorhus** [comment]
Thanks for the suggestions, but not something I'm interested in. This project is done. Opening up for translations adds a bunch of overhead on my part. Sorry. Would be better to fork and release it as a different app.
