### ISSUE TITLE
Incorrect navbar box shadow on Windows 10

### ISSUE THREAD

**Issue by rmdwirizki** [sindresorhus/anatine#135]
![image](https://cloud.githubusercontent.com/assets/13674295/22171603/08ffc186-dfc4-11e6-817f-7d7ff426de39.png)

**Comment by immigrantsheep** [comment]
On linux mint 18.1 as well

**Comment by jorgicio** [comment]
The same happens in Gentoo with MATE.

**Comment by SamVerschueren** [comment]
It's on every platform. It's just hard to keep up with the changes the mobile development team of Twitter does. So someone has to step up and do a PR in order to fix this.

**Comment by sindresorhus** [comment]
I'm just going to deprecate this up. Keeping it up to date is unsustainable.

**Comment by SamVerschueren** [comment]
I agree, it might even be easier to create a standalone Twitter client in Electron and use the API's than keeping this working correctly.
