### ISSUE TITLE
Cross when reading DM or viewing image

### ISSUE THREAD

**Issue by darenju** [sindresorhus/anatine#14]
On OS X, the X button to go back to the previous view is behind the window controls.

It could be good (if possible) to place this button in the top right corner of the window, where there's room for that.

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/anatine/commit/850405be5772cfc22e94fd79a716887ffcb56f72.

**Comment by darenju** [comment]
(y) Awesome, good job @JayBizzle.
