### ISSUE TITLE
Tweet actions should always be at the bottom of the tweet

### ISSUE THREAD

**Issue by paulmolluzzo** [sindresorhus/anatine#23]
Right now the tweet actions (reply, RT, like) are just below the text of the tweet. For shorter tweets or when the window is wide enough that the avatar is taller than the content, this puts the actions higher than the bottom of the avatar, which looks odd.

![screen shot 2016-05-10 at 8 17 47 pm](https://cloud.githubusercontent.com/assets/737065/15166454/e8146f8a-16ec-11e6-8a64-ba97b596efa5.png)

**Comment by paulmolluzzo** [comment]
@sindresorhus Can we get a "has PR" label?

**Comment by sindresorhus** [comment]
Done https://github.com/sindresorhus/anatine/labels/has%20PR

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/anatine/issues/24.
