### ISSUE TITLE
Show the number of new tweets in the tooltip of the tray icon

### ISSUE THREAD

**Issue by PhiLhoSoft** [sindresorhus/anatine#27]
And, perhaps, for Windows users (and maybe Linux ones), in the title of the window...

One potential issue is to define "new tweets". Since when?

I think the more sensible, if supported by your UI framework, is "since the application has lost the focus".
This includes closing the frame (to the tray), minimizing it, bringing another application to front, focusing on an application on another screen...

Otherwise, it could be based on user actions (close button, minimize one, tray icon click...).

**Comment by sindresorhus** [comment]
Can you elaborate on how this is useful? Why is the number of new tweets important?

**Comment by PhiLhoSoft** [comment]
It is certainly not a compelling feature, just a goody.
It allows to see, at least, there are new tweets (for those with few subscriptions... no longer me, I admit), and perhaps to see if there are enough new ones to be worth going back to the app. :smile: 

Alternatively, there might be a little icon change, like Skype does when you receive a new message. Or both! :stuck_out_tongue:

**Comment by sindresorhus** [comment]
I've thought about this for a while and gonna pass on it. I don't think it's something most would need. Thanks for the suggestion, though :)
