### ISSUE TITLE
Port for Instagram?

### ISSUE THREAD

**Issue by tofagerl** [sindresorhus/anatine#28]
This seems like it would be really easy to port to an Instagram client. In fact, I switched out the URL with www.instagram.com/mobile, and it worked out of the box, though of course it was clunky since it still acted like a twitter client. 

Anyway, I'm not a good enough developer to do it, and I certainly don't expect @sindresorhus to do it, but if someone DID do it, that would be amazing, and I would love it! Also, "Instatine"... COME ON!

**Comment by sindresorhus** [comment]
Yeah, that would be cool! I don't have time to maintain yet another app, but I encourage someone to do it. I'm happy to keep this issue open.

**Comment by tofagerl** [comment]
Great, hope someone who wants to learn electron and react takes this on, seems like good project to get started with.

**Comment by bjarneo** [comment]
@tofagerl I'm up for it. Give me a couple of hours :)

**Comment by bjarneo** [comment]
@tofagerl Here you go: https://github.com/bjarneo/instatine

**Comment by tofagerl** [comment]
Loving it :)
Already filed the first bug ;p

**Comment by sindresorhus** [comment]
👍

**Comment by terkelg** [comment]
I also did a Instagram Electron app called Ramme, which is vary similar to Anatine.
https://github.com/terkelg/ramme
