### ISSUE TITLE
Submit to Homebrew Cask

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/anatine#3]
https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md

@victorpopkov @vinkla Any of you interested in helping out with this? No worries if not :)

**Comment by victorpopkov** [comment]
Sure, not a problem. Done in https://github.com/caskroom/homebrew-cask/pull/21001.

**Comment by sindresorhus** [comment]
@victorpopkov Thank you! 😀

**Comment by vinkla** [comment]
You're fast @victorpopkov :+1:

**Comment by sindresorhus** [comment]
@victorpopkov Would you mind doing this one too? https://github.com/sindresorhus/anatine/releases/tag/0.2.0 Sorry for bothering you again, but I did a lot of work since the last release and want to get it out now before I dissapear for a few days.

**Comment by victorpopkov** [comment]
Sure. Done in https://github.com/caskroom/homebrew-cask/pull/21009.

**Comment by sindresorhus** [comment]
@victorpopkov Just curious, what's the point of the appcast field if you have to manually bump versions anyways?

**Comment by victorpopkov** [comment]
> @victorpopkov Just curious, what's the point of the appcast field if you have to manually bump versions anyways?

When appcast is set, we can automate the process of checking whether or not the new version has released for the casks that have it and then update the cask accordingly using, for example, `cask-repair` (details in [CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md)) script.

**Comment by sindresorhus** [comment]
@victorpopkov [New version is out](https://github.com/sindresorhus/anatine/releases/tag/0.3.0). Could you update?

**Comment by victorpopkov** [comment]
> @victorpopkov New version is out. Could you update?

Done in https://github.com/caskroom/homebrew-cask/pull/21161.

**Comment by adidalal** [comment]
@sindresorhus `cask-repair -v {{new_version}} anatine` will automatically change the appropriate values and submit a PR, for future reference. (details in [CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md))

**Comment by sindresorhus** [comment]
@adidalal Oh, that's handy. Will try that out next time :)
