### ISSUE TITLE
Add List icon

### ISSUE THREAD

**Issue by mimorisuzuko** [sindresorhus/anatine#31]
How to open List? I would like to go to List by selecting from the menu. In Twitter official client on os x, user can view List by selecting from left menu. I wish the feature like that.
![_2016-05-12_15_34_10](https://cloud.githubusercontent.com/assets/12094729/15206091/796f6776-1857-11e6-964d-2e7750027a53.png)

**Comment by sindresorhus** [comment]
I don't think lists are supported yet in the [mobile Twitter version](https://mobile.twitter.com), which is what we use here.

**Comment by mimorisuzuko** [comment]
Sorry, I see.
