### ISSUE TITLE
Restore night mode after close

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/anatine#34]
I noticed that after quitting Anatine, the default theme was set back to white. Is it possible to restore that setting?

**Comment by sindresorhus** [comment]
It should do that. Sounds like a bug. What OS are you on?

// @danhp

**Comment by SamVerschueren** [comment]
Mac OS X 10.11.4

**Comment by danhp** [comment]
On OS X, the Dark Mode is linked to the system's theme.
Likely to be identical to https://github.com/sindresorhus/caprine/issues/71

**Comment by tandrewnichols** [comment]
This also happens if your Macbook sleeps for long enough. E.g. It's in dark mode when I close it at night. In the morning, I open it and the app refreshes and is back in light mode.

**Comment by paulmolluzzo** [comment]
This issue highlighted a couple of possibilities for a solution, and I'd like it if we could resolve the bug and also consider the additional features that @danhp proposes in #35.

@danhp's work will respect your _system_ setting for dark mode and override `anatine` if there is a difference (like if you change the setting and later open `anatine`, or if you have some other software that changes the setting automatically at night).    

I pushed an alternative PR if we want to fix the bug and leave the discussion open on the system setting feature before deciding.

Thoughts anyone?

----

@sindresorhus could you please make an "under discussion" label for issues?

**Comment by sindresorhus** [comment]
> On OS X, the Dark Mode is linked to the system's theme.

It sounded like a nice feature when I first thought of it, but in practice I haven't used it once, as I use OS X Dark Mode permanently, and it has gotten a *lot* of complaints, both here, on Caprine, and on Twitter. The reality is that no other app does this on OS X, so I'm inclined to follow the convention here. Sorry @danhp.
