### ISSUE TITLE
Set BrowserWindow `backgroundColor` option

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/anatine#45]
https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions

Currently when starting up the app in dark mode, there's a white flash the dark mode is applied. We should set the window backgroundColor when in dark mode to fix this.

**Comment by SamVerschueren** [comment]
Wanted to file an issue for the bouncing (or whatever it is called) effect in dark mode. But I guess this will solve that as well.

![anatine](https://cloud.githubusercontent.com/assets/1913805/15270066/20c569dc-1a13-11e6-9697-26a8f0c0318c.gif)

**Comment by sindresorhus** [comment]
Sam: Already fixed in latest Electron version ;)

**Comment by SamVerschueren** [comment]
Nice :)
