### ISSUE TITLE
Limit window size

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/anatine#47]
From https://github.com/sindresorhus/anatine/pull/25#issuecomment-218721006.

We should limit the window width to a set size. (What size?)

It should still be possible to fullscreen the window. Then we would just apply the same fix as `refined-twitter` and limit the width of the container. (Resulting in some white margins on each side, but that's fine since we're fullscreen).

**Comment by paulmolluzzo** [comment]
> We should limit the window width to a set size. (What size?)

`800px`? That matches the style in `refined-twitter`. Maybe we could make the window width max out a little wider so there's a little space and then apply the `max-width` to the content container with CSS.

**Comment by sindresorhus** [comment]
👍
