### ISSUE TITLE
Loading indicator ugly in dark mode

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/anatine#50]
<img width="491" alt="screen shot 2016-05-17 at 14 24 26" src="https://cloud.githubusercontent.com/assets/170270/15314294/31d2bfa2-1c3b-11e6-8b7a-f186947a7321.png">

**Comment by paulmolluzzo** [comment]
The classes for this element are `._7xnAHtWH._3tixQkQf` and it's a gif you can find here: https://ma-0.twimg.com/twitter-assets/responsive-web/web/ltr/spinner26x26.6feaaade6c119627.gif

The rough white edge is part of the gif, so we'd need a new asset to override this one.

**Comment by sindresorhus** [comment]
One of these http://samherbert.net/svg-loaders/

**Comment by danhp** [comment]
Fixed in #61
