### ISSUE TITLE
Figure out a way to not inline the scripts

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/anatine#51]
I had to [inline the vendor scripts](https://github.com/sindresorhus/anatine/blob/2a6ae01d5df4886543225b6d66e87a1ff5ca988f/browser.js#L4-L18) as Electron only supports preloading one script. We need to figure out a better way or fix the Electron bug (https://github.com/electron/electron/issues/5400).

@paulmolluzzo @danhp Thoughts?

**Comment by paulmolluzzo** [comment]
> I know I can load the next ones async inside the first preloaded script, but that get's convoluted fast.

What if we concatenate specific files and `preload` only that generated file?
