### ISSUE TITLE
Changing OSX system to dark mode while Anatine is open is not good

### ISSUE THREAD

**Issue by tandrewnichols** [sindresorhus/anatine#52]
You could call this user error and mark unfixable, but I thought I'd at least report it. It's a good idea not to turn on OSX dark mode _while Anatine is open_.

<img width="445" alt="screen shot 58" src="https://cloud.githubusercontent.com/assets/2755760/15360202/b08b867c-1cda-11e6-9b05-be7571246daa.png">

**Comment by SamVerschueren** [comment]
I believe this is fixed in https://github.com/sindresorhus/anatine/pull/49. They made the Anatine theme independent of the OS theme.

**Comment by sindresorhus** [comment]
Yes, this is fixed in master. I'm planning to do a new release in a few days. Just need to get some other fixes in first.

**Comment by sindresorhus** [comment]
New release is out: https://github.com/sindresorhus/anatine/releases
