### ISSUE TITLE
One window style for all OS?

### ISSUE THREAD

**Issue by belohlavek** [sindresorhus/anatine#57]
I'm currently on Windows and the gray menu bar + win7 windows borders look ugly.
How about designing a cross-platform interface in html? Maybe achieving a cross platform version of this:

![alt text](https://github.com/sindresorhus/anatine/raw/master/media/screenshot-dark.png)

**Comment by sindresorhus** [comment]
Sorry, I'm not interested in maintaining something like that. If you don't like the look of Windows, I'm not sure why you're using it at all or at least why you haven't installed some custom theme or something.

I would recommend at least upgrading to Windows 10 where it look a little bit better ;)

<img width="536" alt="screen shot 2016-05-19 at 23 42 38" src="https://cloud.githubusercontent.com/assets/170270/15401864/9dadcc08-1e1b-11e6-947d-1f195820fe00.png">
<img width="537" alt="screen shot 2016-05-19 at 23 43 23" src="https://cloud.githubusercontent.com/assets/170270/15401865/9db974fe-1e1b-11e6-8543-65991e1e23c3.png">

**Comment by belohlavek** [comment]
Nah, it's not that I dislike W7 default theme, it's that it just doesn't play well with Anatine's style :sweat_smile: 
Understood, will fork and implement cross platform styling myself, thanks for reading :+1:

**Comment by sindresorhus** [comment]
https://github.com/kapetan/titlebar might be helpful
