### ISSUE TITLE
Can't paste into login dialogue

### ISSUE THREAD

**Issue by jeversmann** [sindresorhus/anatine#60]
Being unable to paste makes it difficult to use with password managers.

This is with a fresh unzip of the 0.3.0 Windows version.

**Comment by danhp** [comment]
Doesn't `Ctrl + V` work for you?

**Comment by jeversmann** [comment]
Yea, the hotkey did it. I don't know why I assumed it wouldn't after right-clicking failed. I guess that turns this into a mild convenience thing instead of a usability concern.
