### ISSUE TITLE
Active tab is stuck after clicking it and then tabbing

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/anatine#62]
Changing the top tabs using Ctrl+Tab works fine until I manually click one of the tab manually. Then that tab is stuck highlighted.

![untitled12](https://cloud.githubusercontent.com/assets/170270/15420708/6a11d844-1e98-11e6-8cfc-8d3a9ad3b558.gif)

**Comment by danhp** [comment]
Closed by #77
