### ISSUE TITLE
Don't set disable `webSecurity`

### ISSUE THREAD

**Issue by philstrong** [sindresorhus/anatine#67]
https://twitter.com/torgeir/status/733384789424754689

Not my words but thought you'd like the opportunity to speak up about it

**Comment by paulmolluzzo** [comment]
@sindresorhus is there a motivation behind this setting? If not let's set it to `true`.

// @danhp

**Comment by danhp** [comment]
I'm not too sure what this means the comment we had is:

```
// required for Facebook active ping thingy
webSecurity: false,
```

**Comment by sindresorhus** [comment]
Yes, it's needed for logging in with 2FA. Otherwise it never logs in. Seems CSP (webSecurity) is for some reason preventing the 2FA script. I think an immediate fix to the security issue would be to `nodeIntegration: false`. We should still look into how to remove `webSecurity: false` while working with 2FA.

**Comment by paulmolluzzo** [comment]
> I think an immediate fix to the security issue would be to `nodeIntegration: false`.

Isn't that necessary for the vendor script loading that @danhp did using `require`?

**Comment by sindresorhus** [comment]
Yes.

I looked into it now and it seems that `nodeIntegration: true` conflicts with the jQuery script on the [2FA](https://en.wikipedia.org/wiki/Two-factor_authentication) page. When `nodeIntegration: false` and not using `preload` it works. So, I'm not really sure what our options are now. I don't think it's possible to just disable `nodeIntegration` just for the 2FA page. And we need `nodeIntegration` for the IPC communication. Suggestions?
