### ISSUE TITLE
Keyboard shortcuts stopped working (at least on OSX)

### ISSUE THREAD

**Issue by tandrewnichols** [sindresorhus/anatine#69]
They definitely did work at some point. I used "gg" a lot (although I typically had to hit it twice to get all the way to the top . . . presumably once to get to what _was_ the top when I started scrolling and once to get to the top of new content). Now "gg" doesn't work. "Cmd + n" starts a new tweet (even though the docs say just "n"), but "Cmd + gg" (which doesn't really even make sense) does not.

**Comment by paulmolluzzo** [comment]
There is no <kbd>CMD</kbd> required, it's just <kbd>g</kbd> <kbd>g</kbd>. Make sure you're in the window and not in a text field someplace (click the background area or something).

**Comment by sindresorhus** [comment]
Should be fixed in 0.4.2: https://github.com/sindresorhus/anatine/releases/tag/0.4.2
