### ISSUE TITLE
Dark mode and page down have the same keyboard shortcut

### ISSUE THREAD

**Issue by uschek** [sindresorhus/anatine#72]
<kbd>Ctrl</kbd> <kbd>d</kbd> triggers both at the same time.

Dark mode: https://github.com/sindresorhus/anatine/blob/e083f8cc5ae25dc21f6b775d9be371f85ccbab19/menu.js#L308
Page down: https://github.com/sindresorhus/anatine/blob/e083f8cc5ae25dc21f6b775d9be371f85ccbab19/browser.js#L145

**Comment by sindresorhus** [comment]
Oops. I guess we can change dark mode to be Cmd/Ctrl+Shift+D then.
