### ISSUE TITLE
Unable to pan window

### ISSUE THREAD

**Issue by dkouvdis** [sindresorhus/anatine#81]
- If I am top of the page scroll, I can pan the window around
- If I am not top of the page, I am unable to pan the window around

**Comment by paulmolluzzo** [comment]
You mean you can scroll left/right at the top of the page but not after scrolling down? Are you on the home or some other page?

I can't scroll left/right anywhere, so maybe I'm just misunderstanding the issue. If you could record a gif that'd be helpful. If not but can list steps to reproduce that would be equally helpful.

**Comment by SamVerschueren** [comment]
Experiencing the same. What he means is that you can drag the entire window the normal way when the scroll position is 0. But after you have scrolled a little bit down, it seems like the drag handle of the window disappeared and you can't move the window anymore.

**Comment by dkouvdis** [comment]
@SamVerschueren is correct.

**Comment by SamVerschueren** [comment]
Did a screen capture

![dragg](https://cloud.githubusercontent.com/assets/1913805/15963922/d8f9060a-2f15-11e6-9829-f92417db8fa5.gif)

I tried to look into this but couldn't find anything to be honest. The `-webkit-app-region: drag` style is still aplied to the header when scrolling down but somehow this isn't working.

**Comment by dkouvdis** [comment]
Imo, the application should not overlap the window's title bar - should shift the application down. I usually double click any application title bar to maximise it's window, but this doesnt.

Design change, yes I know :(

OSX user
