### ISSUE TITLE
Scale profile picture when window is too small

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/anatine#85]
I think we should set the `max-width` to `100%` in order to scale the picture a little bit down if the view becomes to narrow.

![screen shot 2016-06-10 at 12 20 17](https://cloud.githubusercontent.com/assets/1913805/15961583/ca75035a-2f05-11e6-86d0-52295e9216c1.png)

**Comment by sindresorhus** [comment]
👍
