### ISSUE TITLE
Alt+Shift key combination issue (Linux)

### ISSUE THREAD

**Issue by NerveClasp** [sindresorhus/anatine#89]
Alt+Shift key combination is often used to switch input languages on Linux(/Windows) and it leads to opening of File menu in Anatine. Please fix. Great app nevertheless. Thanks!

-

Anatine 0.4.2
Electron 1.1.2
linux x64 4.4.0-18-generic

**Comment by sindresorhus** [comment]
What keyboard shortcut is the problem?

**Comment by NerveClasp** [comment]
Alt + Shift
Steps to reproduce:
1. Open app.
2. Hold down "Alt" (Option on a Mac) and press "Shift"
Expected Result: no menus are open in the app.
Actual Result: File menu opens.

**Comment by sindresorhus** [comment]
Anatine doesn't define the Alt+Shift keyboard shortcut. I tried Alt+Shift on Antine on both Windows and Linux and neither triggered the file menu.

**Comment by NerveClasp** [comment]
If possible, please test it on Linux Mint 17.3 running Cinnamon 2.8.8 as Desktop Environment. 
https://linuxmint.com/edition.php?id=208

**Comment by sindresorhus** [comment]
Sounds like a problem with Electron. Would you mind opening an issue over there instead? https://github.com/electron/electron/issues Thanks :)
