### ISSUE TITLE
Why hide the profile link?

### ISSUE THREAD

**Issue by davidmerrique** [sindresorhus/anatine#93]
Since the link to the profile is hidden, I have no way to get to my lists. 
Also, the only way to get to my own tweets is via a keyboard shortcut. 
Why are we hiding it?

![screen shot 2016-06-15 at 5 33 41 pm](https://cloud.githubusercontent.com/assets/867522/16098139/8c0e6c46-331f-11e6-85de-13d6e849e316.png)

Thanks

**Comment by sindresorhus** [comment]
Because it's not very useful. I personally almost never visit my own profile. Same with lists. I wanted the app to focus on the important views. You can easily get to your Profile using a keyboard shortcut. I would be open to adding one for Lists too.

**Comment by paulmolluzzo** [comment]
We're also hiding the logout button, and I wouldn't want that to be a shortcut. Currently the only way to log out (that I know of) is to open the inspector and delete the Twitter cookies then quit the application before they're regenerated. What if we show this nav item on your profile?

**Comment by SamVerschueren** [comment]
@paulmolluzzo 
![screen shot 2016-06-16 at 13 35 55](https://cloud.githubusercontent.com/assets/1913805/16115440/46d613c4-33c7-11e6-97d7-e9328fc06407.png)

**Comment by sindresorhus** [comment]
@paulmolluzzo You can logout in the menubar menu.

**Comment by paulmolluzzo** [comment]
@sindresorhus @SamVerschueren Totally didn't even think to look there.

**Comment by ArtskydJ** [comment]
I'd be willing to add a shortcut for lists. (Which would close this issue?)

In twitter, the shortcut is <kbd>g l</kbd>, but in anatine, that shortcut is for likes. If I make the PR, what should the shortcut be?

**Comment by sindresorhus** [comment]
@ArtskydJ On Twitter, the shortcut for Lists is `g i`. That's what we should use here too.
