### ISSUE TITLE
Menu bar colour issue  - [Dark theme]

### ISSUE THREAD

**Issue by dkouvdis** [sindresorhus/anatine#96]
This came in today. 
- Menu bar colour issue
- New tweets toaster addition, the notification marker on the home icon

![image](https://cloud.githubusercontent.com/assets/2727196/16452878/9fd94eec-3e02-11e6-9eb5-d6765a1f8d6b.png)

**Comment by SamVerschueren** [comment]
See PR #95

**Comment by sindresorhus** [comment]
> New tweets toaster addition

This actually looks ok in dark mode. I tried making it dark and it's hard to see.

**Comment by sindresorhus** [comment]
New release is out: https://github.com/sindresorhus/anatine/releases/tag/0.5.1
