### ISSUE TITLE
Close button not entirely clickable

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/anatine#99]
I experience issues with the close button. Only the top part of the button is clickable. As you can see in the gif when the mouse changes from cursor to hand.

![anatine](https://cloud.githubusercontent.com/assets/1913805/16742334/843b4ad8-47a7-11e6-843d-0d7825e8fb6e.gif)

**Comment by sindresorhus** [comment]
I don't have time to look into this right now. Would appreciate if anyone could.

**Comment by framerate** [comment]
@sindresorhus I got it (for OSX). Not sure which platform it is, but I'm guess since you pushed the X down for OSX to account for the "Traffic Light Bar"
